# ---------------------------------------------------- #
# SINGLE-HEADER TERMINAL USER INTERFACE | VARIATION-UI #
#          VARIATION-UI LIBRARY TEST MAKEFILE          #
# ---------------------------------------------------- #

.PHONY: help run

help:
	@echo ""
	@echo "[ Make List ]"
	@echo " 1. Show make list 'make' or 'make help'"
	@echo " 2. Compile all files and run 'make test'"
	@echo ""

test: 
	@cd base && make compile && make clean
	@cd widget && make compile && make clean

# MADE BY @hanilr #